### ISSUE TITLE
Exception during conversion

### ISSUE THREAD

**Issue by tomas-pluskal** [compomics/ThermoRawFileParser#126]
Hi, I downloaded the latest ThermoRawFileParser 1.3.4 and I see this exception when parsing a .raw file:
```
C:\ThermoRawFileParser>ThermoRawFileParser.exe -i 202112_DIMS_MS4_DDA_Orbitrap_IDX.raw
2021-12-08 09:47:29 INFO Started parsing 202112_DIMS_MS4_DDA_Orbitrap_IDX.raw
2021-12-08 09:47:30 INFO Processing 1280 MS scans
10% 2021-12-08 09:47:31 ERROR An unexpected error occured while parsing file:202112_DIMS_MS4_DDA_Orbitrap_IDX.raw
2021-12-08 09:47:31 ERROR System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at ThermoRawFileParser.Writer.MzMlSpectrumWriter.Write(IRawDataPlus rawFile, Int32 firstScanNumber, Int32 lastScanNumber) in /home/niels/Documents/Development/Projects/ThermoRawFileParser/Writer/MzMlSpectrumWriter.cs:line 577
   at ThermoRawFileParser.RawFileParser.ProcessFile(ParseInput parseInput) in /home/niels/Documents/Development/Projects/ThermoRawFileParser/RawFileParser.cs:line 139
   at ThermoRawFileParser.RawFileParser.TryProcessFile(ParseInput parseInput) in /home/niels/Documents/Development/Projects/ThermoRawFileParser/RawFileParser.cs:line 62
```

The raw file is attached.

[202112_DIMS_MS4_DDA_Orbitrap_IDX.zip](https://github.com/compomics/ThermoRawFileParser/files/7674691/202112_DIMS_MS4_DDA_Orbitrap_IDX.zip)

(originally reported by @robinschmid)

**Comment by tomas-pluskal** [comment]
It seems ThermoRawFileParser produces partial mzML output with 239 scans. The original file has 1280 scans. The conversion crashes at scan 240, which is the first MS level 4 scan... so I suspect it has something to do with the MS level.

**Comment by caetera** [comment]
Hi Tomas, 
It is painful to admit it, but TRFP does not support MS4 or higher at the moment. Most likely it is the reason for the crash. I will investigate more and see if there an easy fix for that

**Comment by caetera** [comment]
It has been a long time indeed.

I have implemented general parsing for MSn scan, i.e. now it should support all possible MS levels. The branch with the feature is 7b7854d8c8512e5f5385cfa1a240ff7e96a38821 and it will be included in the next release.

@tomas-pluskal would you like to test it and provide some feedback? and if so let me know if you build from the source or I should build a beta version for you.

**Comment by tomas-pluskal** [comment]
Hi @caetera 
It would be great if you could provide a beta build for us. One of my postdocs is now building a library of MSn (MS3 and MS4) spectra, so I can ask her to test your build.

**Comment by caetera** [comment]
Hi @tomas-pluskal,

Here is the latest beta build: https://syddanskuni-my.sharepoint.com/:u:/g/personal/vgor_bmb_sdu_dk/EeJ50TcZl35OpplVv2ZT7hEBL4gudhEsGoFz1UHgOJXzLw?e=cyvvaS 
Please, not, that it also includes some other changes, most important one is adding precursor intensity, that was not supported earlier (#125).

**Comment by corinnabrungs** [comment]
Hi @caetera, 

I tried the converter with our Orbitrap-IDX data (up to MS5) and it worked well. Attached you can find an MS4 scan and all precursors are marked with a dashed line. Thanks for fixing the issue. 

![image](https://user-images.githubusercontent.com/53823597/170252081-d9addd9b-c727-472c-ab69-c1d327f2f7eb.png)

**Comment by caetera** [comment]
Hi @corinnabrungs,
good to know it works. I will close the issue in a couple of days, but feel free to reopen it, if necessary.

**Comment by caetera** [comment]
New release has been published.

**Comment by tomas-pluskal** [comment]
Thanks a lot! :)
