### ISSUE TITLE
Cannot parse raw file under both Windows 10 or Linux

### ISSUE THREAD

**Issue by armadillocommander** [compomics/ThermoRawFileParser#13]
The error message on Linux:

2018-08-16 13:27:05,156 INFO ThermoRawFileParser.CentroidedMgfExtractor - Started parsing /home/yiming/ThermoRawFileParser/QC.raw
2018-08-16 13:27:05,196 ERROR ThermoRawFileParser.CentroidedMgfExtractor - Error opening (ThermoFisher.CommonCore.RawFileReader.Facade.RawFileLoader) - /home/yiming/ThermoRawFileParser/QC.raw

The error message on Windows 10:
2018-08-16 13:29:23,334 INFO ThermoRawFileParser.CentroidedMgfExtractor - Started parsing QC.raw
2018-08-16 13:29:23,385 ERROR ThermoRawFileParser.MainClass - An unexpected error occured:
2018-08-16 13:29:23,396 ERROR ThermoRawFileParser.MainClass - System.Reflection.TargetInvocationException: Method invocation failed on Method[FileFactory] Type[ThermoFisher.CommonCore.RawFileReader.RawFileReaderAdapter] Assembly[ThermoFisher.CommonCore.RawFileReader.dll] ---> System.ApplicationException: Only 64 bit applications are supported by this project
   at ThermoFisher.CommonCore.RawFileReader.Utilities.Validate64Bit()
   at ThermoFisher.CommonCore.RawFileReader.RawFileAccess.Create(String fileName)
   at ThermoFisher.CommonCore.RawFileReader.RawFileReaderAdapter.FileFactory(String fileName)
   --- End of inner exception stack trace ---
   at ThermoFisher.CommonCore.Data.ObjectFactory`1.FileFactory(String fileName)
   at ThermoFisher.CommonCore.Data.Business.RawFileReaderFactory.ReadFile(String fileName)
   at ThermoRawFileParser.CentroidedMgfExtractor.Extract()
   at ThermoRawFileParser.MainClass.Main(String[] args)

**Comment by nielshulstaert** [comment]
Hi,

The underlying Thermo library only works on 64 bit systems. Could this be your problem?

Best regards,

Niels

**Comment by nielshulstaert** [comment]
Hi,

I encountered the same issue under Windows 10, it seems that I have to use the x64 build option explicitly (no problems when running on linux). The latest release (1.0.4) should work on Windows now, could you give it a try?

My apologies for reopening this, I drew the wrong conclusion from your stacktrace, I'm pretty new to .NET.

Best regards,

Niels
