### ISSUE TITLE
Gzip does not work in BioContainers Docker container (missing library)

### ISSUE THREAD

**Issue by RalfG** [compomics/ThermoRawFileParser#92]
Seems like the container is missing `libMonoPosixHelper.so`

```
❯ docker run --rm -it -v $(pwd):/workdir -w /workdir quay.io/biocontainers/thermorawfileparser:1.2.3--1 thermorawfileparser -i data/mzml/A1.raw --gzip
2020-10-28 14:19:05 INFO Started parsing data/mzml/A1.raw
2020-10-28 14:19:08 ERROR An unexpected error occured:
2020-10-28 14:19:08 ERROR System.DllNotFoundException: /usr/local/lib/../lib/libMonoPosixHelper.so
  at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative.CreateZStream(System.IO.Compression.CompressionMode,bool,System.IO.Compression.DeflateStreamNative/UnmanagedReadOrWrite,intptr)
  at System.IO.Compression.DeflateStreamNative.Create (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean gzip) [0x0004a] in <6e58314266ea48d58d73486babe33a96>:0 
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean leaveOpen, System.Boolean gzip) [0x0002d] in <6e58314266ea48d58d73486babe33a96>:0 
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionMode mode, System.Boolean leaveOpen, System.Int32 windowsBits) [0x00000] in <6e58314266ea48d58d73486babe33a96>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Compression.DeflateStream..ctor(System.IO.Stream,System.IO.Compression.CompressionMode,bool,int)
  at System.IO.Compression.GZipStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionMode mode, System.Boolean leaveOpen) [0x00006] in <6e58314266ea48d58d73486babe33a96>:0 
  at System.IO.Compression.GZipStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionMode mode) [0x00000] in <6e58314266ea48d58d73486babe33a96>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Compression.GZipStream..ctor(System.IO.Stream,System.IO.Compression.CompressionMode)
  at ThermoRawFileParser.Writer.SpectrumWriter.ConfigureWriter (System.String extension) [0x000ad] in <41119cf2ddce4ea78f6356000798cca0>:0 
  at ThermoRawFileParser.Writer.MzMlSpectrumWriter.Write (ThermoFisher.CommonCore.Data.Interfaces.IRawDataPlus rawFile, System.Int32 firstScanNumber, System.Int32 lastScanNumber) [0x00026] in <41119cf2ddce4ea78f6356000798cca0>:0 
  at ThermoRawFileParser.RawFileParser.ProcessFile (ThermoRawFileParser.ParseInput parseInput) [0x0016a] in <41119cf2ddce4ea78f6356000798cca0>:0 
  at ThermoRawFileParser.RawFileParser.Parse (ThermoRawFileParser.ParseInput parseInput) [0x00176] in <41119cf2ddce4ea78f6356000798cca0>:0 
  at ThermoRawFileParser.MainClass.RegularParametersParsing (System.String[] args) [0x008a0] in <41119cf2ddce4ea78f6356000798cca0>:0
```

**Comment by caetera** [comment]
Hi @RalfG ,

to the best of my knowledge biocontainer image is abandoned so-to-say. You can use [caetera/thermorawfileparser](https://hub.docker.com/repository/docker/caetera/thermorawfileparser) as immediate substitution. It is basically the same biocontainer, just with the latest version of TRFP.

**Comment by bgruening** [comment]
@caetera don't let this @ypriverol hear ;) Its not at all abandoned.
Here you can find a container for all version https://quay.io/repository/biocontainers/thermorawfileparser?tag=latest&tab=tags

If those container does not work with gzip, then a dependency is missing and should be declated in the conda recipe.

**Comment by ypriverol** [comment]
We are using it in production and it works perfectly well.

**Comment by caetera** [comment]
@bgruening good to know it is alive, however, the container is 3 releases behind the code of TRFP. Is it possible to set biocontainer to be built every time master is commited? I know it is possible on the DockerHub, but not familiar with Quay.

**Comment by bgruening** [comment]
You need to create a proper release, then an automatic PR to bioconda is created and can be merged.

**Comment by caetera** [comment]
Thank you for explanation @bgruening 
What is considered "proper" release? There are seems to be three releases in GitHub (https://github.com/compomics/ThermoRawFileParser/releases) that do not have image in biocontainers.

**Comment by RalfG** [comment]
The Bioconda bot updates Python packages automatically, I guess by looking at PyPI releases. Not sure if there's an option for non-Python packages.

**Comment by caetera** [comment]
I checked the bioconda repository and figured out that the latest versions were not built because of failing test - https://github.com/bioconda/bioconda-recipes/pull/24101 .

It fails at
> BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpm_794hs8/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld/:/opt/host-conda-bld -v /home/circleci/project/recipes/thermorawfileparser:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash`

and the error is

> 15:11:16 BIOCONDA INFO (OUT) Traceback (most recent call last):
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
> 15:11:16 BIOCONDA INFO (OUT)     sys.exit(main())
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
> 15:11:16 BIOCONDA INFO (OUT)     execute(sys.argv[1:])
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
> 15:11:16 BIOCONDA INFO (OUT)     verify=args.verify, variants=args.variants)
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
> 15:11:16 BIOCONDA INFO (OUT)     notest=notest, need_source_download=need_source_download, variants=variants)
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
> 15:11:16 BIOCONDA INFO (OUT)     notest=notest,
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2151, in build
> 15:11:16 BIOCONDA INFO (OUT)     newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1518, in bundle_conda
> 15:11:16 BIOCONDA INFO (OUT)     output['checksums'] = create_info_files(metadata, files, prefix=metadata.config.host_prefix)
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1188, in create_info_files
> 15:11:16 BIOCONDA INFO (OUT)     copy_license(m)
> 15:11:16 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 763, in copy_license
> 15:11:16 BIOCONDA INFO (OUT)     "source root dir or in recipe root dir (with meta.yaml)".format(src_file))
> 15:11:16 BIOCONDA INFO (OUT) ValueError: License file given in about/license_file (/opt/recipe/LICENSE) does not exist in source root dir or in recipe root dir (with meta.yaml)

I am fairly new to Bioconda recepies and, thus, all help in fixing it will be much appreciated.

**Comment by martenson** [comment]
@caetera I think the bioconda build should be fixed (and package updated) with https://github.com/bioconda/bioconda-recipes/pull/26729

**Comment by bernt-matthias** [comment]
... and the follow up https://github.com/bioconda/bioconda-recipes/pull/26756 which solved the issue mentioned in the first message of the thread for me.
